# Site settings
title: Okan Vurdu
email: okanvurdu@gmail.com
description: Kişisel karalamalar ve deneyimlerin bir dökümü
baseurl: ""
url: "http://okanvurdu.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
