# Site settings
title: Okan Vurdu
email: okanvurdu@gmail.com
description: Kişisel karalamalar ve deneyimlerin bir dökümü
baseurl: ""
url: "http://okanvurdu.com"
twitter_username: vurdunio
github_username:  okanvurdu

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
permalink: "/:title"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      is_post: true
